version: "3.7"
services:
  mediawiki:
    env_file:
      - envs/my-new-system.env
    container_name: mwm_mediawiki
    image: dataspects/mediawiki:1.35.0-2103040820
    ports:
      - 80:80
      - 443:443
    volumes:
      # MediaWiki
      - ./mediawiki_root/w/LocalSettings.php:/var/www/html/w/LocalSettings.php
      - ./mediawiki_root/w/extensions:/var/www/html/w/extensions
      - ./mediawiki_root/w/skins:/var/www/html/w/skins
      - ./mediawiki_root/w/vendor:/var/www/html/w/vendor
      - ./mediawiki_root/w/images:/var/www/html/w/images
      # MediaWiki Manager
      - ./logs:/var/www/logs
      # MediaWiki Manager >>> Restic
      - ./conf/restic/restic_password:/var/www/restic_password
      - ./restic_data:/var/www/html/restic-repo
      # MediaWiki Manager >>> Clone
      - ./cloneLocation:/var/www/cloneLocation
      # Apache
      - ./conf/apache/sites-available:/etc/apache2/sites-available
      # UI
      - ./mediawiki_root/ui:/var/www/html/ui
  mwmapi:
    container_name: mwmapi
    image: dataspects/mwmapi:210303
    environment:
      - MWAPI=http://mediawiki/w/api.php
      - MWROOT=/home/lex/mediawiki-manager/mediawiki_root/w
    ports:
      - 3000:3000
  mysql:
    container_name: mwm_mariadb
    image: mariadb:10.5.5
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}